### ISSUE TITLE
Nice code! A question on the log-likelihood function.

### ISSUE THREAD

**Issue by HeraldoAlmeida** [aimir/irt#1]
Hi, I'm Heraldo Almeida, professor at the Computer and Electronics Engineering Dept. at Federal University of Rio de Janeiro, Brazil. 

I loved your IRT code (simple and precise!), but I could not understand the formulation you use for the log-likelihood function in python functions learn_abcd() and learn_theta(). 

It looks like you start from the log of the PDF of a normal distribution and then add/subtract ln(2*P) for each correct/wrong answer.

Where does this formulation come from? Did you developed it by yourself? Could you provide some reference source that explains it better?

**Comment by aimir** [comment]
Hi there! Thank you for your kind words.

As for the log-likelihood function, it is basically equivalent to taking the log-likelihood of the results we got:

- For every right answer, then a factor of log1p(2 * p - 1) = log(2 * p) is indeed added to the overall log-likelihood.
- For every wrong answer, a factor of log1p(1 - 2 * p) = log(2 * (1-p)) is added.
- Since the likelihood of a wrong answer is indeed 1-p, this will add up to be the right log-likelihood, up to the factor of (2 ^ (#the number of students / items)).
- This factor shouldn't matter for the optimization, as it remains the same throughout the process.

My reasoning behind doing things this way is that can utilize numpy's powerful vectorization methods (it doesn't do that right now, but I'll probably add this functionality soon) and that it uses log1p which has better precision around log(1) (as is the case in the first iteration, where all the likelihoods p are about 1/2. This is just whatever made sense to me - I tried to look up how it should be done and came up short. If there is a more canonical way to approach this, I would appreciate any reference to such a method.

Either way, it seems that indeed some comment about what happens there should be added to the code. I will probably add this as well on version 0.0.3.

Amir.
