### ISSUE TITLE
isolated usage of logistic model

### ISSUE THREAD

**Issue by akhilbatra898** [aimir/irt#2]
Hi

I really liked the implementation, especially two way likelyhood estimation for theta and question parameters as well.

I am wondering If I want to do something custom with the 2PL probabilities. Is it good idea to use your  2PL or 4PL model. since you have tweaked the formulae a bit for optimisations.

>  The 2PL likelihood function is given here by
> 
>    ``LOGISTIC(a * x + b)``.

I understand it won't have any effect on final theta estimation, but in my use case I want to explicitly use probability of solving a question then update theta heuristically.

**Comment by aimir** [comment]
Hi! I'm so sorry for not answering sooner...
Sure, it's possible to use this in isolation.
Please note, though, that my use of a,b is different from the usual parameterization of he 2PL model, in order to allow for better preformance. Usually the parametrization is such that the likelihood is given by LOGISTIC(a * (x - b)), so that b is the "difficulty" of the question.
To convert from my parameters to the usual ones:
a_usual = a_my
b_usual = -b_my / a_my
To convert back from the usual parameterization to mine:
a_my = a_usual
b_my = -a_usual * b_usual
Again, so sorry for only answering now... Please let me know if this answers your question!
Best regards.
